### ISSUE TITLE
Excessive memory amount requested

### ISSUE THREAD

**Issue by Alessandro994** [pkorus/multiscale-prnu#1]
Hi, while I was running the demo_localization script after following the instruction to setup everything I got this error: 

> Error using UGM_makeEdgeVEC
> Requested 4294999697x3044903065436228352 (17179869184.0GB) array exceeds maximum array size preference

which after a while I find out it comes from the _UGM_makeEdgeVE.m_ script when the **useMex** variable has value 1 and the if statement passes.
Commenting out this if-else clauses and using only the "else" procedure the demo finishes works fine.
Do you have any idea why?
Thank you for this precious code anyway!

**Comment by pkorus** [comment]
I'm not sure - it looks like some problem in the UGM library. Interestingly, it appears to be compiler-related.  I get the same error on my new system with a newly-compiled library:

```
# strings -a UGM_makeEdgeVEC.mexa64 | grep GCC
GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```

But on the same machine, the library which I compiled last year works correctly. 

```
strings -a UGM_makeEdgeVEC.mexa64 | grep GCC
GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-4)
```

At the moment, I don't have time to follow up on this. If you want, I can send you my old compiled version of UGM (or just the problematic file). Anyway, once the adjacency matrix is created (e.g., with useMex set to false), it will be cached as a .mat file and reused later.

**Comment by Alessandro994** [comment]
I thought it could be a compiler-related issue because as I ran the _make_all_ script I received tons of warning related to the version of my GCC compiler, no error though.
Anyway, thanks for your support!

**Comment by MattJKTaylor** [comment]
I ran into a similar memory issue with UGM_makeEdgeVEC on a different project and managed to fix the issue by forcing mex to use the 32 bit API with the parameter -compatibleArrayDims when compiling UGM:

`mex -compatibleArrayDims -Imex -outdir compiled mex/UGM_makeEdgeVEC.c`

[MATLAB - Upgrade MEX Files to Use 64-Bit API](https://uk.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html?requestedDomain=true)

Running UGM_makeEdgeVEC on GCC 4.9 compiled with no warnings and ran without the previous memory error so give it a try. I couldn't find any other information anywhere on the issue so this may work for you too.

**Comment by pkorus** [comment]
This successively fixes the problem. Thanks! 

In the context of this repository, the fix is to change the compilation flag in UGM Toolbox, i.e., line 7 in `3rd-party/ugm/mexAll.m`.
