### ISSUE TITLE
There is no function of NoiseExtractFromImage

### ISSUE THREAD

**Issue by jxw950605** [pkorus/multiscale-prnu#3]
Hi~ Thank you very much for sharing the code.
when I tried to run several functions, I ran into the same problem: the lack of NoiseExtractFromImage function.
Read the instructions you provided, it should be a function of wavelet denoising. Can you provide it?

**Comment by pkorus** [comment]
This function is a 3rd party dependency. Use `python2 ./configure.py dependencies` to download all of them. See `readme.md` for details. The function can be also downloaded manually from:
http://dde.binghamton.edu/download/camera_fingerprint/CameraFingerprint_1.1.zip
