### ISSUE TITLE
UGM_2011 size has changed from 467330 to 476869

### ISSUE THREAD

**Issue by neboduus** [pkorus/multiscale-prnu#4]
Hi the configuration script goes into an infinite loop continuing printing the following:

```
...
Fetching file UGM_2011.zip
Downloading: UGM_2011.zip (476869b) [####################]
Cached copy of UGM_2011.zip is invalid, cleaning up...
...

```

This is because the UGM package present at https://www.cs.ubc.ca has changed size from 467330 to 476869 due to an update. I just had to change the value of the structure sizes from the script and its working now.

**Comment by pkorus** [comment]
Thanks, fixed + added attempt counter
